public class CRC_ShuffleMasterWrapper {
    @AuraEnabled public integer order;
    @AuraEnabled public Datetime assignmentDateTime;
    @AuraEnabled public String assignmentId;
    @AuraEnabled public String assignmentName;
    @AuraEnabled public String stockID;
    @AuraEnabled public String stockName;
    @AuraEnabled public String branchId;
    @AuraEnabled public String branchName;
    @AuraEnabled public String state;
    @AuraEnabled public String assignmentType;
    @AuraEnabled public String processStatus;
    @AuraEnabled public Double releaseChargesTotal;
    @AuraEnabled public String providerSLA;
    @AuraEnabled public String releaseAssignmentId;
    @AuraEnabled public Datetime rpFollowUPDateTime;
    @AuraEnabled public Datetime dueDateTime;
    @AuraEnabled public Integer remainingTimeInMins;
    @AuraEnabled public String providerName;
    @AuraEnabled public Decimal distance;
         //public String voState;
        // public Datetime slaCalculatePickupDateTime;
        // public String dynamicIcon;

    }