public class CustomConstants {
	public static final String CARVIO = 'CARVIO';
    public static final String TRADEREV = 'TRADEREV';
    public static final String UPCOMING = 'Upcoming';
    public static final String ACTIVE = 'Active';
    public static final String PENDING = 'Pending';
    public static final Integer INCREMENT_VALUE_LESS_THAN_1000 = 50;
    public static final Integer INCREMENT_VALUE_GREATER_THAN_1000 = 100;
    public static final Integer INCREMENT_BASE = 1000;
    public static final Integer INCREMENT_MULTIPLY_FOR_ACTIVE = 2;
    public static final Integer INCREMENT_MULTIPLY_FOR_UPCOMING = 2;
    public static final String STATUS_OF_LISTING = 'Status_of_Listing__c';
}